### ISSUE TITLE
concurrent_hash_map

### ISSUE THREAD

**Issue by HBSDLJZ** [pmem/libpmemobj-cpp#1258]
When I write a large amount of data, what can I do to improve the write throughput of the hash table?
thank you~~

**Comment by igchor** [comment]
For concurrent_hash_map there is not much you can do, unfortunately. You could try to allocate key/values before inserting them to the hash_map (in a single transaction) and putting them to some per-thread pmem::obj::vector, and then, just storing pointers inside hash_map.

However, a better idea might be to use radix_tree (https://github.com/pmem/libpmemobj-cpp/blob/master/include/libpmemobj%2B%2B/experimental/radix_tree.hpp) and combine multiple inserts into a single transaction. This would result in a significant speed up. If you need concurrent inserts, I would suggest trying to shard radix_tree (e.g. create an array of 1000 radix_trees and based on hash of the key, decide to which radix_tree the insert should go. you can then protect each shard by a lock). 

You can also use inline_string (https://github.com/pmem/libpmemobj-cpp/blob/master/include/libpmemobj%2B%2B/experimental/inline_string.hpp)  with radix_tree instead of regular pmem::obj::string, which decreases total number of allocations. You can take a look at this example: https://github.com/pmem/libpmemobj-cpp/blob/master/examples/radix_tree/radix_tree_inline_string.cpp

**Comment by lukaszstolarczuk** [comment]
I hope it helped. In case of more questions don't hesitate to ask. Closing this one for now.
