### ISSUE TITLE
pmem::transaction_out_of_memory

### ISSUE THREAD

**Issue by HBSDLJZ** [pmem/libpmemobj-cpp#1259]
When I perform a large number of write stress tests on the concurrent_hash_map, this error occurs. How can I solve it?
thankyou~

**Comment by HBSDLJZ** [comment]
Thank you very much, I am very moved!

**Comment by lukaszstolarczuk** [comment]
I hope it helped. In case of more questions don't hesitate to ask. Closing this one for now.

**Comment by swordfate** [comment]
When I run [`array.cpp`,](https://github.com/pmem/libpmemobj-cpp/blob/master/examples/array/array.cpp) I encounter the same problem. :(
After checking the code, I found that the error occurred when persist an object new_array in the pool as `persistent_ptr<int[]> new_array = make_persistent<int[]>(size);
`. 

What confuses me is that although the parameter `size` is large, it is still **smaller than the PMem pool size**. Why does this error still occur?
I will be very grateful if you can give me some explanations. :) @igchor @lukaszstolarczuk

**Comment by igchor** [comment]
This is because of the allocator design in pmemobj. The allocator divides all available memory into multiple regions which happen to be ~16GB. The exact value is defined here: https://github.com/pmem/pmdk/blob/master/src/include/libpmemobj/base.h#L40 

If you're interested in allocator internals, I encourage your to take a look at Chapter 16 in our (free) book: https://pmem.io/books/
