### ISSUE TITLE
Creating arrays

### ISSUE THREAD

**Issue by Kuvesz** [pmem/libpmemobj-cpp#329]
Hi!

I tried creating an application based on your arrays example, but simpler and I always get an error like this:
`error: no matching function for call to ‘make_persistent<uint64_t [size]>()’`
The relevant code pieces are the struct that describes an entry:
```
struct entry {
		p<uint64_t> size;
		persistent_ptr<uint64_t[]> entry;
};
```
And the line where I actually try to create a persistent array:
`new_entry->entry = make_persistent<uint64_t[]>(size);`

I might be making a really obvious mistake so please just bear with me here.

**Comment by igchor** [comment]
Hello,

The error message tells that there is no function for make_persistent for arrays that takes no parameters, but notice that the type in error message is not uint64_t[] but uint64_t[size] which are different types.

In libpmemobj-cpp we support 2 types of array creation:
1. Creation of arrays which length is passed in runtime (as make_persistent parameter):
`persistent_ptr<uint64_t[]> entry;`
`entry = make_persistent<uint64_t[]>(size);`

2. Creation of sized arrays:
`persistent_ptr<uint64_t[100]> entry;`
`entry = make_persistent<uint64_t[100]>();`

Notice that in the first case, you must provide size as make_persistent parameter and in the second one, you pass size in compile time, as part of array type (value 100 must be know in compile time). In the second case you CANNOT pass size argument to make_persistent (otherwise you will get compiler error). My guess is that you mixed those two types.

If that didn't solve you're issue, could you please provide full compiler output and part of the code which causes this error?

**Comment by Kuvesz** [comment]
Oh sorry, I kinda messed up by copying the wrong line from the code, the correct one would be:
`new_entry->entry = make_persistent<uint64_t[size]>();`
I also tried it the other way, which on pmem.io is said to be equivalent `new_entry->entry = make_persistent<uint64_t[]>(size);`, this resulted in the following error:
```
error: no matching function for call to ‘make_persistent<uint64_t []>(uint64_t&)’
     entry = make_persistent<uint64_t[]>(size)
```
Also to me it seems that I'm doing pretty much the same thing as the first option you gave me but I also have to mention that by the error log it seems that only the pp_if_not_array variants of make_persistent get even tried.

**Comment by Kuvesz** [comment]
Never mind, I'm just stupid and didn't realize that those were in a differnet header file and only included make_persistent.hpp and not make_persistent_array.hpp.

Thanks for the help anyway. :)
