### ISSUE TITLE
is there any problem is we do not call defragment after failure recovery process

### ISSUE THREAD

**Issue by chencheng1560** [pmem/libpmemobj-cpp#768]
# QUESTION: 

## Details

Hi, I trying the concurrent hash map and test the recovery time after a failure. I found the sample code always call FUNCTION: defragment() after each failure, however, the defragment() is very time-consuming. May I know is it possible we do not call defragment() function after failure? Does call defragment() a 'must-have' behavior?

**Comment by pbalcer** [comment]
The short answer is: no.

The long answer requires a little bit of an explanation. The reason we recommend running defragmentation on startup is because of the perceived nature of memory allocations. Usually, when an application runs out of memory, it crashes and starts anew with an empty heap. This behavior enables the application to continue functioning, even if in a degraded state. For example, caching in-memory databases, such as Redis or memcached, that can struggle with memory fragmentation, can be restarted as a last resort fix for that problem.
That's not the case with Persistent Memory, where even fragmentation is persistent. So when an application encounters an ENOMEM error from persistent allocation, the method of just letting it restart no longer solves the problem. Badly designed software could get into a cycle of starting up, finding no memory available, and crashing.
Hence, an easy solution to solve that cycle is to introduce a defrag step on startup. But this is not required, and you can employ different methods of dealing with fragmentation. For example, you can perform defragmentation only when memory allocation fails. Or you can have a background thread that monitors the heap and periodically runs the defrag function on a subset of objects.

The defragmentation functionality is fairly flexible, and you can use it as elaborately as you need to.
It's also important to point out that, if your application does not suffer from fragmentation, and the steady-state space-amplification is acceptable, then running defrag might not be necessary at all.

**Comment by chencheng1560** [comment]
Get it! thanks for your quick reply

**Comment by lukaszstolarczuk** [comment]
It seems the question is fully answered
